# Generated by Django 4.0.1 on 2022-01-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='Move',
            field=models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissor')], max_length=1),
        ),
    ]
