# Generated by Django 4.0.1 on 2022-01-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_round_delete_bot_remove_player_move_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='Move',
            field=models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
    ]
