# Generated by Django 4.0.1 on 2022-01-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_round_name_alter_round_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Round',
            new_name='Rounds',
        ),
    ]
