# Generated by Django 4.0.1 on 2022-01-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_round_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
    ]
